/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interFaces;

import codes.EmployeeClass;
import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Vimukthi Pramudantha
 */
public class AssistenAddEmployee extends javax.swing.JFrame {

    /**
     * Creates new form AssistenAddEmployee
     */
    public AssistenAddEmployee() {
        initComponents();
        fillComboFormTextFile();
        fillComboFormTextFileDepartment();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        EID = new javax.swing.JTextField();
        EName = new javax.swing.JTextField();
        EAge = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        EAdress = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        EDepartment = new javax.swing.JComboBox<>();
        EDesignation = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Add Employees");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Employee ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Employee Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Age");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Current Address");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        EID.setToolTipText("Enter Employee ID");
        jPanel1.add(EID, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 220, -1));

        EName.setToolTipText("Enter Employee Name");
        jPanel1.add(EName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 220, -1));

        EAge.setToolTipText("Enter Employee Age");
        jPanel1.add(EAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 110, -1));

        EAdress.setColumns(20);
        EAdress.setRows(5);
        EAdress.setToolTipText("Enter Address");
        jScrollPane1.setViewportView(EAdress);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 220, 80));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Department");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Designation");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        EDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department" }));
        jPanel1.add(EDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 150, -1));

        EDesignation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Designation" }));
        jPanel1.add(EDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 150, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 360));

        setSize(new java.awt.Dimension(653, 368));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void fillComboFormTextFile() {

        String filePath = "D:\\Files\\Designation.txt";
        File file = new File(filePath);

        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            Object[] lines = br.lines().toArray();

            for (int i = 0; i < lines.length; i++) {
                String line = lines[i].toString();
                EDesignation.addItem(line);
            }

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Sorry! something went wrong, " + ex, "designation names", JOptionPane.ERROR_MESSAGE);

        }
    }
    
    public void fillComboFormTextFileDepartment() {

        String filePath = "D:\\Files\\Department.txt";
        File file = new File(filePath);

        try {
            BufferedReader DE = new BufferedReader(new FileReader(file));
            Object[] lines = DE.lines().toArray();

            for (int i = 0; i < lines.length; i++) {
                String line = lines[i].toString();
                EDepartment.addItem(line);
            }

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Sorry! something went wrong, " + ex, "designation names", JOptionPane.ERROR_MESSAGE);

        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String employeeID = EID.getText();
        String employeeName = EName.getText();
        String employeeAge = EAge.getText();
        String employeeAdress = EAdress.getText();
        String employeeDesignation = EDesignation.getSelectedItem().toString();
        String employeeDepartment = EDepartment.getSelectedItem().toString();
        
         if (employeeID.isEmpty()  || employeeName.isEmpty() || employeeAge.isEmpty() || employeeAdress.isEmpty()) {
             JOptionPane.showMessageDialog(rootPane, "Fileds cannot be empty when adding a new user.", "Add a new Employee ", JOptionPane.WARNING_MESSAGE);
            return;
        }
        EmployeeClass user = new EmployeeClass(employeeName,employeeID,employeeAge,employeeAdress,employeeDesignation,employeeDepartment);
        if(user.addNewEmployee())
             JOptionPane.showMessageDialog(rootPane, "Employee added successfully.", "Add a new Employee", JOptionPane.INFORMATION_MESSAGE);
        else{
            JOptionPane.showMessageDialog(rootPane, "Something went wrong with the application. Will be fixing it soon.", "Add a new Employee", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        HRAssistent assisten = new HRAssistent();
        assisten.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssistenAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssistenAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssistenAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssistenAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssistenAddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea EAdress;
    private javax.swing.JTextField EAge;
    private javax.swing.JComboBox<String> EDepartment;
    private javax.swing.JComboBox<String> EDesignation;
    private javax.swing.JTextField EID;
    private javax.swing.JTextField EName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
